"""PDF report generation for forensic evidence."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image

from ..core.config import settings


def generate_match_report(
    job_id: str,
    matches: list,
    timeline: list,
    output_path: Path | None = None,
) -> Path:
    """Generate a PDF report for video analysis matches."""
    if not output_path:
        output_path = settings.reports_dir / f"{job_id}_report.pdf"
    
    doc = SimpleDocTemplate(str(output_path), pagesize=A4)
    story = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#20e3b2"),
        spaceAfter=30,
    )
    
    story.append(Paragraph("KAAVAL Forensic Match Report", title_style))
    story.append(Spacer(1, 0.2 * inch))
    
    story.append(Paragraph(f"<b>Report ID:</b> {job_id}", styles["Normal"]))
    story.append(Paragraph(f"<b>Generated:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", styles["Normal"]))
    story.append(Spacer(1, 0.3 * inch))
    
    story.append(Paragraph("<b>Match Summary</b>", styles["Heading2"]))
    story.append(Spacer(1, 0.1 * inch))
    
    match_data = [["Person ID", "Name", "Confidence", "Time Range"]]
    for match in matches:
        match_data.append([
            str(match.get("person_id", "N/A")),
            match.get("person_name", "Unknown"),
            f"{match.get('confidence', 0) * 100:.1f}%",
            f"{match.get('start_time', 0):.1f}s - {match.get('end_time', 0):.1f}s",
        ])
    
    match_table = Table(match_data, colWidths=[1 * inch, 2 * inch, 1 * inch, 2 * inch])
    match_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#20e3b2")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ]
        )
    )
    story.append(match_table)
    story.append(Spacer(1, 0.3 * inch))
    
    if timeline:
        story.append(Paragraph("<b>Timeline Events</b>", styles["Heading2"]))
        story.append(Spacer(1, 0.1 * inch))
        for event in timeline:
            story.append(
                Paragraph(
                    f"<b>{event.get('timestamp', 0):.1f}s</b>: {event.get('label', 'Event')} "
                    f"(Confidence: {event.get('confidence', 0) * 100:.1f}%)",
                    styles["Normal"],
                )
            )
            story.append(Spacer(1, 0.05 * inch))
    
    story.append(Spacer(1, 0.2 * inch))
    story.append(
        Paragraph(
            "<i>This report was generated by KAAVAL AI System. "
            "All matches are subject to verification by authorized personnel.</i>",
            styles["Normal"],
        )
    )
    
    doc.build(story)
    return output_path

